spring:
  datasource:
    url: ${DATABASE_CONNECTION_STRING}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      schema: ${DATABASE_SCHEMA}
  rabbitmq:
    host: ${RABBITMQ_HOST}
    port: 5672
    username: ${RABBITMQ_USERNAME}
    password: ${RABBITMQ_PASSWORD}
    listener:
      simple:
        concurrency: 2
        max-concurrency: 5
        prefetch: 20
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
      default_schema: ${DATABASE_SCHEMA}
    show-sql: false
    properties:
      hibernate:
        format_sql: false
        use_sql_comments: false
        default_schema: ${DATABASE_SCHEMA}

  flyway:
    enabled: ${FLYWAY_ENABLED:true}
    baseline-on-migrate: ${FLYWAY_BASELINE_ON_MIGRATE:true}
    create-schemas: true
    schemas: ${DATABASE_SCHEMA}
    default-schema: ${DATABASE_SCHEMA}
    locations: ${FLYWAY_LOCATIONS:classpath:db/migration}

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope:
              - email
              - profile
            REDIRECT_URL: ${GOOGLE_REDIRECT_URL}
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/v2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://openidconnect.googleapis.com/v1/userinfo
            user-name-attribute: sub

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL}

management:
  endpoints:
    web:
      exposure:
        include: health,info

sendgrid:
  api-key: ${SENDGRID_API_KEY}
  from-email: ${SENDGRID_FROM_EMAIL}
  from-name: ${SENDGRID_FROM_NAME}

JWT_SECRET: ${JWT_SECRET}
JWT_EXPIRY: ${JWT_EXPIRY}
JWT_REFRESH_EXPIRY: ${JWT_REFRESH_EXPIRY}
OTP_EXPIRY_TIME_IN_MINUTES: ${OTP_EXPIRY_TIME_IN_MINUTES}
FRONTEND_URL: ${FRONTEND_URL}
DOMAIN: ${DOMAIN}
do:
  spaces:
    bucket: ${DO_Spaces_Bucket}
    region: ${DO_Spaces_Region}
    endpoint: ${DO_Spaces_Endpoint}
    cdn-url: ${DO_Spaces_CDN_URL}
    access-key: ${DO_Spaces_Access_Key}
    secret-key: ${DO_Spaces_Secret_Key}
logging:
  level:
    root: INFO
    org.hibernate.SQL: OFF
    org.hibernate.type.descriptor.sql.BasicBinder: OFF
    com.apollo.auth: INFO
